"""Add is_active column

Revision ID: efc4e12ec9e5
Revises: 9aa7306bbb60
Create Date: 2024-10-24 15:23:56.079053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc4e12ec9e5'
down_revision = '9aa7306bbb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
