"""initial

Revision ID: 932d4fc6d8b0
Revises: 
Create Date: 2024-10-24 17:11:47.674069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932d4fc6d8b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
